//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySample.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_history
    {
        public int Seq { get; set; }
        public string SN { get; set; }
        public string Location { get; set; }
        public System.DateTime DateIn { get; set; }
        public System.DateTime DateOut { get; set; }
        public string SaleOrderNo { get; set; }
        public string TrakingNo { get; set; }
        public string ModelNo { get; set; }
    
        public virtual Location Location1 { get; set; }
    }
}
