//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySample.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public string MODELNO { get; set; }
        public int VERSION { get; set; }
        public string FG { get; set; }
        public string MODEL1 { get; set; }
        public Nullable<bool> SOLE { get; set; }
        public string DESC { get; set; }
        public Nullable<System.DateTime> FP_DATE { get; set; }
        public Nullable<bool> LABOR_W { get; set; }
        public Nullable<int> SNBegin { get; set; }
        public Nullable<int> SNEnd { get; set; }
        public byte[] ViewFile { get; set; }
        public byte[] SPFile { get; set; }
        public Nullable<bool> Commercial { get; set; }
        public string Brand { get; set; }
        public Nullable<int> MinQuantity { get; set; }
    }
}
