//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySample.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneCode
    {
        public int Zone { get; set; }
        public string Code { get; set; }
    }
}
